<?xml version='1.0' encoding='utf-8' ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<!--
<ATGCOPYRIGHT>

 * Copyright (C) 2009 Art Technology Group, Inc.
 * All Rights Reserved.  No use, copying or distribution of this
 * work may be made except in accordance with a valid license
 * agreement from Art Technology Group.  This notice must be
 * included on all copies, modifications and derivatives of this
 * work.
 *
 * Art Technology Group (ATG) MAKES NO REPRESENTATIONS OR WARRANTIES
 * ABOUT THE SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. ATG SHALL NOT BE
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 * Dynamo is a trademark of Art Technology Group, Inc.
 </ATGCOPYRIGHT>*/

A template for displaying samples headlines generated by a JSP in shared gear view.

Author: J Marino 

The following paramaters are passed in by the JSP that calls this template:

articleGearUrl is the base URL that points back to the Gear to display a particular
               article.  The template calculates the full URL which includes the base 
			   URL and an article id parameter which is used by the gear to retrieve the
			   article from the service provider.
			     

-->
	<xsl:output method="html" version="4.0" encoding="utf-8"/>
	<xsl:param name="articleGearUrl"/>
	<xsl:param name="headlinesUrl"/>
	<xsl:template match="/">
		<br/>
		<table>
			<xsl:apply-templates select="//category"/>
		</table>
	</xsl:template>
	<xsl:template match="category">
		<tr>
			<td bgcolor="#cccccc">
				<font size="1">
					<b>
						<xsl:value-of select="category.name"/>
					</b>
				</font>
			</td>
		</tr>
		<tr/>
		<xsl:apply-templates select="headline"/>
	</xsl:template>
	<xsl:template match="headline">
		<tr>
			<td>
				<font size="-2">
					<b>
						<xsl:text disable-output-escaping="yes"><![CDATA[<a href="]]></xsl:text>
						<xsl:value-of select="$articleGearUrl"/>
						<xsl:text disable-output-escaping="yes"><![CDATA[&]]></xsl:text>articleID=<xsl:value-of select="headline.id"/><xsl:text disable-output-escaping="yes"><![CDATA[">]]></xsl:text>
						<xsl:value-of select="headline.caption"/>
						<xsl:text disable-output-escaping="yes"><![CDATA[</a>]]></xsl:text>
					</b>
				</font>
			</td>
		</tr>
		<tr>
			<td>
				<font size="-2">
					<i>
						<xsl:value-of select="headline.source"/>&#160;&#160;
						<xsl:variable name="month">
							<xsl:value-of select="substring(headline.date,5,2)">
							</xsl:value-of>
						</xsl:variable>
						<xsl:choose>
							<xsl:when test="$month='01'">January</xsl:when>
							<xsl:when test="$month='02'">February</xsl:when>
							<xsl:when test="$month='03'">March</xsl:when>
							<xsl:when test="$month='04'">April</xsl:when>
							<xsl:when test="$month='05'">May</xsl:when>
							<xsl:when test="$month='06'">June</xsl:when>
							<xsl:when test="$month='07'">July</xsl:when>
							<xsl:when test="$month='08'">August</xsl:when>
							<xsl:when test="$month='09'">September</xsl:when>
							<xsl:when test="$month='10'">October</xsl:when>
							<xsl:when test="$month='11'">November</xsl:when>
							<xsl:when test="$month='12'">December</xsl:when>
						</xsl:choose>&#160;
						<xsl:value-of select="substring(headline.date,7,2)">
						</xsl:value-of>,&#160;<xsl:value-of select="substring(headline.date,1,4)"></xsl:value-of>
					</i>  </font>
			</td>
		</tr>
	</xsl:template>
</xsl:stylesheet>
<!-- Stylus Studio meta-information - (c)1998-2001 eXcelon Corp.
<metaInformation>
<scenarios ><scenario default="yes" name="Scenario1" url="file://c:\workspace\app\xmlprotocol\main\xmlprotocol.war\web\data\generic.headlines.xml" htmlbaseurl="" processortype="internal" commandline="" additionalpath="" additionalclasspath=""/></scenarios><MapperInfo  srcSchemaPath="" srcSchemaRoot="" destSchemaPath="" destSchemaRoot="" />
</metaInformation>
-->
<!-- @version $Id: //app/portal/version/10.0.3/xmlprotocol/xmlprotocol.war/templates/generic.shared.headlines.xsl#2 $$Change: 651448 $-->
