delete from das_account
delete from das_group_assoc
delete from dss_server_id
delete from dss_coll_scenario
delete from dss_scenario_info
delete from dss_xref
delete from epub_wf_server_id
delete from epub_coll_workflow
delete from epub_workflow_info
