


--  @version $Id: //product/ARF/version/10.0.3/ARF/DW/Search/sql/xml/search_datawarehouse_init.xml#1 $$Change: 651360 $
-- This file contains SQL statements which will initialize theSearch Datawarehouse directory level tables.

START TRANSACTION;
INSERT INTO ARF_SEARCH_PROJECT (ID, NPROJECT_ID, NAME, NAME_EN, MOST_RECENT, DELETED) VALUES (0, '0', 'Unspecified', 'Unspecified', 1, 0);
INSERT INTO ARF_SEARCH_ENVIRONMENT (ID, NENVIRONMENT_ID, NAME, NAME_EN, PROJECT_ID, MOST_RECENT, DELETED) VALUES (0, '0', 'Unspecified', 'Unspecified', 0, 1, 0);

INSERT INTO ARF_QUERY_TYPE (ID, NTYPE_ID, NAME, NAME_EN) VALUES (0, '0', 'Unspecified', 'Unspecified');
INSERT INTO ARF_QUERY_TYPE (ID, NTYPE_ID, NAME, NAME_EN) VALUES (1, 'SimpleSearchEvent', 'Simple Search', 'Simple Search');
INSERT INTO ARF_QUERY_TYPE (ID, NTYPE_ID, NAME, NAME_EN) VALUES (2, 'BrowseEvent', 'Browse', 'Browse');
INSERT INTO ARF_QUERY_TYPE (ID, NTYPE_ID, NAME, NAME_EN) VALUES (3, 'StructuredSearchEvent', 'Structured Search', 'Structured Search');
INSERT INTO ARF_QUERY_TYPE (ID, NTYPE_ID, NAME, NAME_EN) VALUES (4, 'SimilarDocSearchEvent', 'Similar Doc Search', 'Similar Doc Search');
INSERT INTO ARF_QUERY_TYPE (ID, NTYPE_ID, NAME, NAME_EN) VALUES (5, 'CategorizeSearchEvent', 'Categorize Search', 'Categorize Search');
INSERT INTO ARF_QUERY_TYPE (ID, NTYPE_ID, NAME, NAME_EN) VALUES (6, 'CategoryNavigationEvent', 'Category Navigation', 'Category Navigation');

INSERT INTO ARF_PROFILE_TYPE (ID, REPOSITORY_NAME) VALUES (0, 'Unspecified');
INSERT INTO ARF_PROFILE_TYPE (ID, REPOSITORY_NAME) VALUES (1, 'UserProfiles');
INSERT INTO ARF_PROFILE_TYPE (ID, REPOSITORY_NAME) VALUES (2, 'InternalUserProfiles');

INSERT INTO ARF_CONTENT (ID, TITLE, URL_KEY, URL, CONTENT_TYPE) VALUES (0, 'Unspecified', 'Unspecified', 'Unspecified', 'Unspecified');

INSERT INTO ARF_SEARCH_TOPIC (ID, NTOPIC_ID, NAME, NAME_EN, MOST_RECENT, DELETED) VALUES (0, '0', 'Unspecified', 'Unspecified', 1, 0);

INSERT INTO ARF_WORD_GROUP (ID, NAME, HASH_VALUE, NUM_WORDS) VALUES (0, 'Unspecified', '0', 0);
INSERT INTO ARF_CUSTTRM_GRP (ID, NAME, HASH_VALUE, LENGTH) VALUES (0, 'Unspecified', '0', 0);
INSERT INTO ARF_FINDTRM_GRP (ID, NAME, HASH_VALUE, LENGTH) VALUES (0, 'Unspecified', '0', 0);
INSERT INTO ARF_NULLTRM_GRP (ID, NAME, HASH_VALUE, LENGTH) VALUES (0, 'Unspecified', '0', 0);
INSERT INTO ARF_NULXTRM_GRP (ID, NAME, HASH_VALUE, LENGTH) VALUES (0, 'Unspecified', '0', 0);
INSERT INTO ARF_TOPIC_GROUP (ID, NAME, HASH_VALUE, LENGTH) VALUES (0, 'Unspecified', '0', 0);

INSERT INTO ARF_SEARCH_RULE_GRP (ID, NAME, HASH_VALUE, LENGTH) VALUES (0, 'Unspecified', '0', 0);
INSERT INTO ARF_SEARCH_CONFIG (ID, NSEARCH_CONFIG_ID, NAME, DESCRIPTION, RECORD_LAST_UPDATE, RECORD_START_DATE, RECORD_END_DATE, MOST_RECENT, DELETED) VALUES (0, '0', 'Unspecified', 'Unspecified', null, null, null, 0, 0);

INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (0, 'Unspecified');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (1, 'aerospace');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (2, 'airlines');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (3, 'apparel');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (4, 'appliances');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (5, 'automotive');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (6, 'business');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (7, 'computer');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (8, 'cooking');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (9, 'crafts');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (10, 'ecommerce');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (11, 'financial');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (12, 'food');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (13, 'healthcare');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (14, 'hotels');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (15, 'housewares');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (16, 'HR');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (17, 'insurance');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (18, 'jewelry');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (19, 'legal');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (20, 'manufacturing');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (21, 'media');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (22, 'personal_care');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (23, 'pets');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (24, 'sports_outdoors');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (25, 'telecommunications');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (26, 'tools');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (27, 'toys');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (28, 'yard_garden');
INSERT INTO ARF_DICTIONARY_ADAPTER (ID, NAME) VALUES (29, 'TermTool');

INSERT INTO ARF_SEARCH_RULE_TYPE (ID, NSEARCH_RULE_TYPE_ID, NAME, NAME_EN) VALUES (0, '0', 'Unspecified', 'Unspecified');
INSERT INTO ARF_SEARCH_RULE_TYPE (ID, NSEARCH_RULE_TYPE_ID, NAME, NAME_EN) VALUES (1, 'exclusion', 'Result Exclusion', 'Result Exclusion');
INSERT INTO ARF_SEARCH_RULE_TYPE (ID, NSEARCH_RULE_TYPE_ID, NAME, NAME_EN) VALUES (2, 'position', 'Positioning', 'Positioning');
INSERT INTO ARF_SEARCH_RULE_TYPE (ID, NSEARCH_RULE_TYPE_ID, NAME, NAME_EN) VALUES (3, 'redirection', 'Redirection', 'Redirection');

INSERT INTO ARF_SRCH_SITE_CONSTR (ID, NAME, HASH_VALUE, LENGTH) VALUES (0, 'Unspecified', '0', 0);

INSERT INTO ARF_QUERY
(ID, QUERY_DAY_ID, QUERY_TIME_ID, NQUERY_ID, EXTERNAL_PROFILE_ID, INTERNAL_PROFILE_ID, PROFILE_TYPE_ID,
SEARCH_ENVIRONMENT_ID, LANGUAGE_ID, QUERY_TYPE_ID, QUESTION_ID, SEGCLSTR_ID, DEMOGRAPHIC_ID,
SITE_VISIT_ID, WORD_GROUP_ID, CUSTOM_TERM_GROUP_ID, FINDER_TERM_GROUP_ID,  NULL_TERM_GROUP_ID, NULX_TERM_GROUP_ID, TOPIC_GROUP_ID, SELECTED_TOPIC_GROUP_ID, 
SEARCH_CONFIG_ID, SEARCH_RULE_GROUP_ID, RESPONSE_TIME, TOP_SCORE, RESULTS_COUNT, LAST_SELECTED, SITE_ID, SITE_CONSTR_ID)
VALUES (0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

        
commit;


