####################################################
#
# Generic Makefile
#
# Nathan Abramson
# Copyright 1996  Art Technology Group
#
# Creation date Fri Oct  4 17:04:11 EDT 1996
#
####################################################

include ./srcroot/sourcemaint/Makefile.pre

####################################################

####################################################

include ./srcroot/sourcemaint/Makefile.post

####################################################


